### ISSUE TITLE
Missing config or config instructions

### ISSUE THREAD

**Issue by tylercollier** [emckay/saga-example#1]
Perhaps you can commit to git a `config.js` sample file. Because there is not one right now so the tests (and presumably the app) can't run.

```
$ npm test

> unit_01_es6_warmup@1.0.0 test /home/tylercollier/repos/saga-example
> mocha --compilers js:babel-core/register --require ./test/test_helper.js --recursive

module.js:339
    throw err;
    ^

Error: Cannot find module '../../config.js'
```

Also, the README mentions a `local` branch, but there is none.

**Comment by emckay** [comment]
There is a `config.example.js` in the root directory.

I will add a note about that to the README and clean up the stuff about a `local` branch.

Thanks!

**Comment by tylercollier** [comment]
Oops! Thanks! I created a Firebase account and got this working. Thanks for providing the database sample JSON and the note to make Firebase's database public readable! It was cool to try your app and see it fetch the data over websockets. It was so fast I thought it had pre-downloaded it!
